name: Build ESP32-P4 Firmware

on:
  workflow_dispatch:
    inputs:
      example_path:
        description: 'Example path'
        required: true
        default: 'examples/esp-idf/11_esp_brookesia_phone'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.1
          target: esp32p4
          path: ${{ github.event.inputs.example_path }}
          command: |
            export SDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.esp32p4;../../../config/esp32p4_rev3_x.defaults"
            idf.py set-target esp32p4 build

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-P4-Brookesia-Firmware
          path: |
            ${{ github.event.inputs.example_path }}/build/bootloader/bootloader.bin
            ${{ github.event.inputs.example_path }}/build/partition_table/partition-table.bin
            ${{ github.event.inputs.example_path }}/build/esp_brookesia_demo.bin
            ${{ github.event.inputs.example_path }}/build/flash_args
